
import java.awt.Color;
import java.io.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Brandon
 */
public class JairlineGUI extends javax.swing.JFrame {

    /**
     * Creates new form JairlineGUI
     */
    public JairlineGUI() throws IOException, ClassNotFoundException{
        initComponents();
        myPlane = new Airplane();
        checkSeatingAvailability();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngropupClasses = new javax.swing.ButtonGroup();
        btngroupSeatingPosition = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        rbtnFirstClass = new javax.swing.JRadioButton();
        rbtnEconomyClass = new javax.swing.JRadioButton();
        lblTravelers = new javax.swing.JLabel();
        txtFldNumTraveling = new javax.swing.JFormattedTextField();
        lblFirstClassSeating = new javax.swing.JLabel();
        f00 = new javax.swing.JButton();
        f10 = new javax.swing.JButton();
        f20 = new javax.swing.JButton();
        f30 = new javax.swing.JButton();
        f01 = new javax.swing.JButton();
        f11 = new javax.swing.JButton();
        f21 = new javax.swing.JButton();
        f31 = new javax.swing.JButton();
        f02 = new javax.swing.JButton();
        f12 = new javax.swing.JButton();
        f22 = new javax.swing.JButton();
        f32 = new javax.swing.JButton();
        f03 = new javax.swing.JButton();
        f13 = new javax.swing.JButton();
        f23 = new javax.swing.JButton();
        f33 = new javax.swing.JButton();
        f04 = new javax.swing.JButton();
        f14 = new javax.swing.JButton();
        f24 = new javax.swing.JButton();
        f34 = new javax.swing.JButton();
        lblEconomySeating = new javax.swing.JLabel();
        e00 = new javax.swing.JButton();
        e10 = new javax.swing.JButton();
        e20 = new javax.swing.JButton();
        e30 = new javax.swing.JButton();
        e40 = new javax.swing.JButton();
        e50 = new javax.swing.JButton();
        e01 = new javax.swing.JButton();
        e11 = new javax.swing.JButton();
        e21 = new javax.swing.JButton();
        e31 = new javax.swing.JButton();
        e41 = new javax.swing.JButton();
        e51 = new javax.swing.JButton();
        e02 = new javax.swing.JButton();
        e12 = new javax.swing.JButton();
        e22 = new javax.swing.JButton();
        e32 = new javax.swing.JButton();
        e42 = new javax.swing.JButton();
        e52 = new javax.swing.JButton();
        e03 = new javax.swing.JButton();
        e13 = new javax.swing.JButton();
        e23 = new javax.swing.JButton();
        e33 = new javax.swing.JButton();
        e43 = new javax.swing.JButton();
        e53 = new javax.swing.JButton();
        e04 = new javax.swing.JButton();
        e14 = new javax.swing.JButton();
        e24 = new javax.swing.JButton();
        e34 = new javax.swing.JButton();
        e44 = new javax.swing.JButton();
        e54 = new javax.swing.JButton();
        e05 = new javax.swing.JButton();
        e15 = new javax.swing.JButton();
        e25 = new javax.swing.JButton();
        e35 = new javax.swing.JButton();
        e45 = new javax.swing.JButton();
        e55 = new javax.swing.JButton();
        e06 = new javax.swing.JButton();
        e16 = new javax.swing.JButton();
        e26 = new javax.swing.JButton();
        e36 = new javax.swing.JButton();
        e46 = new javax.swing.JButton();
        e56 = new javax.swing.JButton();
        e07 = new javax.swing.JButton();
        e17 = new javax.swing.JButton();
        e27 = new javax.swing.JButton();
        e37 = new javax.swing.JButton();
        e47 = new javax.swing.JButton();
        e57 = new javax.swing.JButton();
        e08 = new javax.swing.JButton();
        e18 = new javax.swing.JButton();
        e28 = new javax.swing.JButton();
        e38 = new javax.swing.JButton();
        e48 = new javax.swing.JButton();
        e58 = new javax.swing.JButton();
        e09 = new javax.swing.JButton();
        e19 = new javax.swing.JButton();
        e29 = new javax.swing.JButton();
        e39 = new javax.swing.JButton();
        e49 = new javax.swing.JButton();
        e59 = new javax.swing.JButton();
        e010 = new javax.swing.JButton();
        e110 = new javax.swing.JButton();
        e210 = new javax.swing.JButton();
        e310 = new javax.swing.JButton();
        e410 = new javax.swing.JButton();
        e510 = new javax.swing.JButton();
        e011 = new javax.swing.JButton();
        e111 = new javax.swing.JButton();
        e211 = new javax.swing.JButton();
        e311 = new javax.swing.JButton();
        e411 = new javax.swing.JButton();
        e511 = new javax.swing.JButton();
        e012 = new javax.swing.JButton();
        e112 = new javax.swing.JButton();
        e212 = new javax.swing.JButton();
        e312 = new javax.swing.JButton();
        e412 = new javax.swing.JButton();
        e512 = new javax.swing.JButton();
        e013 = new javax.swing.JButton();
        e113 = new javax.swing.JButton();
        e213 = new javax.swing.JButton();
        e313 = new javax.swing.JButton();
        e413 = new javax.swing.JButton();
        e513 = new javax.swing.JButton();
        e014 = new javax.swing.JButton();
        e114 = new javax.swing.JButton();
        e214 = new javax.swing.JButton();
        e314 = new javax.swing.JButton();
        e414 = new javax.swing.JButton();
        e514 = new javax.swing.JButton();
        lblRow = new javax.swing.JLabel();
        lblRow0 = new javax.swing.JLabel();
        lblRow1 = new javax.swing.JLabel();
        lblRow2 = new javax.swing.JLabel();
        lblRow3 = new javax.swing.JLabel();
        lblRow4 = new javax.swing.JLabel();
        lblRow5 = new javax.swing.JLabel();
        lblRow6 = new javax.swing.JLabel();
        lblRow7 = new javax.swing.JLabel();
        lblRow8 = new javax.swing.JLabel();
        lblRow9 = new javax.swing.JLabel();
        lblRow10 = new javax.swing.JLabel();
        lblRow11 = new javax.swing.JLabel();
        lblRow12 = new javax.swing.JLabel();
        lblRow13 = new javax.swing.JLabel();
        lblRow14 = new javax.swing.JLabel();
        lblSeatAvability = new javax.swing.JLabel();
        btnBookIt = new javax.swing.JButton();
        lblSeatingPosition = new javax.swing.JLabel();
        rbtnWindow = new javax.swing.JRadioButton();
        rbtnAsile = new javax.swing.JRadioButton();
        rbtnMiddle = new javax.swing.JRadioButton();
        txtFldAvailableSeats = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("J Airline");

        lblClass.setText("Class");

        btngropupClasses.add(rbtnFirstClass);
        rbtnFirstClass.setText("First");
        rbtnFirstClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFirstClassActionPerformed(evt);
            }
        });

        btngropupClasses.add(rbtnEconomyClass);
        rbtnEconomyClass.setText("Economy");
        rbtnEconomyClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEconomyClassActionPerformed(evt);
            }
        });

        lblTravelers.setText("Number of Travelers");

        txtFldNumTraveling.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        lblFirstClassSeating.setText("First Class Seating");

        lblEconomySeating.setText("Economy Seating");

        lblRow.setText("Row");

        lblRow0.setText("0");

        lblRow1.setText("1");

        lblRow2.setText("2");

        lblRow3.setText("3");

        lblRow4.setText("4");

        lblRow5.setText("5");

        lblRow6.setText("6");

        lblRow7.setText("7");

        lblRow8.setText("8");

        lblRow9.setText("9");

        lblRow10.setText("10");

        lblRow11.setText("11");

        lblRow12.setText("12");

        lblRow13.setText("13");

        lblRow14.setText("14");

        lblSeatAvability.setText("Seat Availability");

        btnBookIt.setText("Book It");
        btnBookIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookItActionPerformed(evt);
            }
        });

        lblSeatingPosition.setText("Seating Position");

        btngroupSeatingPosition.add(rbtnWindow);
        rbtnWindow.setText("Window");
        rbtnWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnWindowActionPerformed(evt);
            }
        });

        btngroupSeatingPosition.add(rbtnAsile);
        rbtnAsile.setText("Asile");
        rbtnAsile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAsileActionPerformed(evt);
            }
        });

        btngroupSeatingPosition.add(rbtnMiddle);
        rbtnMiddle.setText("Middle (Economy Only)");
        rbtnMiddle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMiddleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnWindow)
                            .addComponent(rbtnAsile)
                            .addComponent(rbtnMiddle)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rbtnFirstClass)
                                .addComponent(rbtnEconomyClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFldNumTraveling)
                                .addComponent(lblTravelers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSeatAvability))
                            .addComponent(btnBookIt)
                            .addComponent(lblSeatingPosition))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtFldAvailableSeats))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblFirstClassSeating)
                        .addGap(147, 147, 147)
                        .addComponent(lblEconomySeating))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(f00)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(f10)
                                .addGap(18, 18, 18)
                                .addComponent(f20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(f30))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(f01)
                                    .addComponent(f02)
                                    .addComponent(f03)
                                    .addComponent(f04))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(f11)
                                    .addComponent(f12)
                                    .addComponent(f13)
                                    .addComponent(f14))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(f21)
                                    .addComponent(f22)
                                    .addComponent(f23)
                                    .addComponent(f24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(f34)
                                    .addComponent(f33)
                                    .addComponent(f32)
                                    .addComponent(f31, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(lblRow0))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblRow4)
                                        .addComponent(lblRow3)
                                        .addComponent(lblRow2)
                                        .addComponent(lblRow1)
                                        .addComponent(lblRow5)
                                        .addComponent(lblRow6)
                                        .addComponent(lblRow7)
                                        .addComponent(lblRow8)
                                        .addComponent(lblRow9)
                                        .addComponent(lblRow10)
                                        .addComponent(lblRow11)
                                        .addComponent(lblRow12)
                                        .addComponent(lblRow13)
                                        .addComponent(lblRow14)))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e00)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e20)
                                        .addGap(18, 18, 18)
                                        .addComponent(e30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e40)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e50))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e01)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e21)
                                        .addGap(18, 18, 18)
                                        .addComponent(e31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e51))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e02)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e22)
                                        .addGap(18, 18, 18)
                                        .addComponent(e32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e42)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e52))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e03)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e23)
                                        .addGap(18, 18, 18)
                                        .addComponent(e33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e43)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e53))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e04)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e24)
                                        .addGap(18, 18, 18)
                                        .addComponent(e34)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e44)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e54))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e05)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e25)
                                        .addGap(18, 18, 18)
                                        .addComponent(e35)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e45)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e55))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e06)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e26)
                                        .addGap(18, 18, 18)
                                        .addComponent(e36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e46)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e56))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e07)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e27)
                                        .addGap(18, 18, 18)
                                        .addComponent(e37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e47)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e57))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e08)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e28)
                                        .addGap(18, 18, 18)
                                        .addComponent(e38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e48)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e58))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e09)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e29)
                                        .addGap(18, 18, 18)
                                        .addComponent(e39)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e49)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e59))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e010)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e110)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e210)
                                        .addGap(18, 18, 18)
                                        .addComponent(e310)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e410)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e510))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e011)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e111)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e211)
                                        .addGap(18, 18, 18)
                                        .addComponent(e311)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e411)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e511))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e012)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e112)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e212)
                                        .addGap(18, 18, 18)
                                        .addComponent(e312)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e412)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e512))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e013)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e113)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e213)
                                        .addGap(18, 18, 18)
                                        .addComponent(e313)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e413)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e513))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(e014)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e114)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e214)
                                        .addGap(18, 18, 18)
                                        .addComponent(e314)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e414)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e514))))
                            .addComponent(lblRow))))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstClassSeating)
                            .addComponent(lblEconomySeating)
                            .addComponent(lblRow))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(f00, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(f01, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(f02, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(f03, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(f04, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(f10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f30, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e00, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e30, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e40, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(e50, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRow0))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(f31, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f32, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f33, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f34, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(f21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(f11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(e01, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(e11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(e21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(e31, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(e41, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(e51, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(e02, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(e12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(e22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(e32, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(e42, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(e52, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblRow1)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblRow2)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRow3)
                                            .addComponent(e03, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e33, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e43, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e53, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRow4)
                                            .addComponent(e04, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e34, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e44, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e54, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRow5)
                                            .addComponent(e05, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e35, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e45, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e55, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRow6)
                                            .addComponent(e06, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e26, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e36, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e46, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e56, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRow7)
                                            .addComponent(e07, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e27, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e37, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e47, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e57, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRow8)
                                            .addComponent(e08, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e28, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e38, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e48, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e58, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRow9)
                                            .addComponent(e09, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e29, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e39, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e49, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e59, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRow10)
                                            .addComponent(e010, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e110, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e210, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e310, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e410, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e510, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(e011, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e111, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e211, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e311, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e411, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e511, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblRow11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(e012, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(e112, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(e212, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(e312, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(e412, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(e512, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(e013, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(e113, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(e213, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(e313, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(e413, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(e513, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(e014, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(e114, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(e214, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(e314, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(e414, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(e514, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lblRow14)))
                                                    .addComponent(lblRow13)))
                                            .addComponent(lblRow12)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblClass, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnFirstClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnEconomyClass)
                        .addGap(18, 18, 18)
                        .addComponent(lblTravelers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFldNumTraveling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSeatingPosition)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnWindow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnAsile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnMiddle)
                        .addGap(18, 18, 18)
                        .addComponent(lblSeatAvability)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFldAvailableSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBookIt)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnEconomyClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEconomyClassActionPerformed
        classChoice = rbtnEconomyClass.getText();
    }//GEN-LAST:event_rbtnEconomyClassActionPerformed

    private void rbtnFirstClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFirstClassActionPerformed
        classChoice = rbtnFirstClass.getText();
    }//GEN-LAST:event_rbtnFirstClassActionPerformed

    private void btnBookItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookItActionPerformed
        myPlane.addPassenger(classChoice,Integer.parseInt(txtFldNumTraveling.getText()), position);   
        checkSeatingAvailability();
        txtFldAvailableSeats.setText(myPlane.returnMessageForSeating());
        txtFldNumTraveling.setText("");
        try{
            myPlane.saveFile();
        }
        catch(IOException e){
            System.out.println("Didnt Work" + e);
        }
        catch(ClassNotFoundException r){
            System.out.println("Didnt Work" + r);
        }
    }//GEN-LAST:event_btnBookItActionPerformed

    private void rbtnWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnWindowActionPerformed
        position = rbtnWindow.getText();
    }//GEN-LAST:event_rbtnWindowActionPerformed

    private void rbtnAsileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAsileActionPerformed
        position = rbtnAsile.getText();
    }//GEN-LAST:event_rbtnAsileActionPerformed

    private void rbtnMiddleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMiddleActionPerformed
        position = rbtnMiddle.getText();
    }//GEN-LAST:event_rbtnMiddleActionPerformed

    private void checkSeatingAvailability(){
        /*FIRST CLASS*/
        if(!myPlane.returnFirstSeating(0,0).equals("")){
            f00.setBackground(Color.red);
        }
        if(!myPlane.returnFirstSeating(0,1).equals("")){
            f10.setBackground(Color.red);
        }
        if(!myPlane.returnFirstSeating(0,2).equals("")){
            f20.setBackground(Color.red);
        }
        if(!myPlane.returnFirstSeating(0,3).equals("")){
            f30.setBackground(Color.red);
        }
        /*NEW ROW*/
        if(!myPlane.returnFirstSeating(1,0).equals("")){
            f01.setBackground(Color.red);
        }
        if(!myPlane.returnFirstSeating(1,1).equals("")){
            f11.setBackground(Color.red);
        }
        if(!myPlane.returnFirstSeating(1,2).equals("")){
            f21.setBackground(Color.red);
        }
        if(!myPlane.returnFirstSeating(1,3).equals("")){
            f31.setBackground(Color.red);
        }
        /*NEW ROW*/
        if(!myPlane.returnFirstSeating(2,0).equals("")){
            f02.setBackground(Color.red);
        }
        if(!myPlane.returnFirstSeating(2,1).equals("")){
            f12.setBackground(Color.red);
        }
        if(!myPlane.returnFirstSeating(2,2).equals("")){
            f22.setBackground(Color.red);
        }
        if(!myPlane.returnFirstSeating(2,3).equals("")){
            f32.setBackground(Color.red);
        }
        /*NEW ROW*/
        if(!myPlane.returnFirstSeating(3,0).equals("")){
            f03.setBackground(Color.red);
        }
        if(!myPlane.returnFirstSeating(3,1).equals("")){
            f13.setBackground(Color.red);
        }
        if(!myPlane.returnFirstSeating(3,2).equals("")){
            f23.setBackground(Color.red);
        }
        if(!myPlane.returnFirstSeating(3,3).equals("")){
            f33.setBackground(Color.red);
        }
        /*NEW ROW*/
        if(!myPlane.returnFirstSeating(4,0).equals("")){
            f04.setBackground(Color.red);
        }
        if(!myPlane.returnFirstSeating(4,1).equals("")){
            f14.setBackground(Color.red);
        }
        if(!myPlane.returnFirstSeating(4,2).equals("")){
            f24.setBackground(Color.red);
        }
        if(!myPlane.returnFirstSeating(4,3).equals("")){
            f34.setBackground(Color.red);
        }
        
        /*ECONOMY*/
        if(!myPlane.returnEconomySeating(0,0).equals("")){
            e00.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(0,1).equals("")){
            e10.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(0,2).equals("")){
            e20.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(0,3).equals("")){
            e30.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(0,4).equals("")){
            e40.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(0,5).equals("")){
            e50.setBackground(Color.red);
        }
        /*NEW ROW*/
        if(!myPlane.returnEconomySeating(1,0).equals("")){
            e01.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(1,1).equals("")){
            e11.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(1,2).equals("")){
            e21.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(1,3).equals("")){
            e31.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(1,4).equals("")){
            e41.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(1,5).equals("")){
            e51.setBackground(Color.red);
        }
        /*NEW ROW*/
        if(!myPlane.returnEconomySeating(2,0).equals("")){
            e02.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(2,1).equals("")){
            e12.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(2,2).equals("")){
            e22.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(2,3).equals("")){
            e32.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(2,4).equals("")){
            e42.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(2,5).equals("")){
            e52.setBackground(Color.red);
        }
        /*NEW ROW*/
        if(!myPlane.returnEconomySeating(3,0).equals("")){
            e03.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(3,1).equals("")){
            e13.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(3,2).equals("")){
            e23.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(3,3).equals("")){
            e33.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(3,4).equals("")){
            e43.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(3,5).equals("")){
            e53.setBackground(Color.red);
        }
        /*NEW ROW*/
        if(!myPlane.returnEconomySeating(4,0).equals("")){
            e04.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(4,1).equals("")){
            e14.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(4,2).equals("")){
            e24.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(4,3).equals("")){
            e34.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(4,4).equals("")){
            e44.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(4,5).equals("")){
            e54.setBackground(Color.red);
        }
        /*NEW ROW*/
        if(!myPlane.returnEconomySeating(5,0).equals("")){
            e05.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(5,1).equals("")){
            e15.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(5,2).equals("")){
            e25.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(5,3).equals("")){
            e35.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(5,4).equals("")){
            e45.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(5,5).equals("")){
            e55.setBackground(Color.red);
        }
        /*NEW ROW*/
        if(!myPlane.returnEconomySeating(6,0).equals("")){
            e06.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(6,1).equals("")){
            e16.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(6,2).equals("")){
            e26.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(6,3).equals("")){
            e36.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(6,4).equals("")){
            e46.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(6,5).equals("")){
            e56.setBackground(Color.red);
        }
        /*NEW ROW*/
        if(!myPlane.returnEconomySeating(7,0).equals("")){
            e07.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(7,1).equals("")){
            e17.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(7,2).equals("")){
            e27.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(7,3).equals("")){
            e37.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(7,4).equals("")){
            e47.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(7,5).equals("")){
            e57.setBackground(Color.red);
        }
        /*NEW ROW*/
        if(!myPlane.returnEconomySeating(8,0).equals("")){
            e08.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(8,1).equals("")){
            e18.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(8,2).equals("")){
            e28.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(8,3).equals("")){
            e38.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(8,4).equals("")){
            e48.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(8,5).equals("")){
            e58.setBackground(Color.red);
        }
        /*NEW ROW*/
        if(!myPlane.returnEconomySeating(9,0).equals("")){
            e09.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(9,1).equals("")){
            e19.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(9,2).equals("")){
            e29.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(9,3).equals("")){
            e39.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(9,4).equals("")){
            e49.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(9,5).equals("")){
            e59.setBackground(Color.red);
        }
        /*NEW ROW*/
        if(!myPlane.returnEconomySeating(10,0).equals("")){
            e010.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(10,1).equals("")){
            e110.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(10,2).equals("")){
            e210.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(10,3).equals("")){
            e310.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(10,4).equals("")){
            e410.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(10,5).equals("")){
            e510.setBackground(Color.red);
        }
        /*NEW ROW*/
        if(!myPlane.returnEconomySeating(11,0).equals("")){
            e011.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(11,1).equals("")){
            e111.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(11,2).equals("")){
            e211.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(11,3).equals("")){
            e311.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(11,4).equals("")){
            e411.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(11,5).equals("")){
            e511.setBackground(Color.red);
        }
        /*NEW ROW*/
        if(!myPlane.returnEconomySeating(12,0).equals("")){
            e012.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(12,1).equals("")){
            e112.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(12,2).equals("")){
            e212.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(12,3).equals("")){
            e312.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(12,4).equals("")){
            e412.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(12,5).equals("")){
            e512.setBackground(Color.red);
        }
        /*NEW ROW*/
        if(!myPlane.returnEconomySeating(13,0).equals("")){
            e013.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(13,1).equals("")){
            e113.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(13,2).equals("")){
            e213.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(13,3).equals("")){
            e313.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(13,4).equals("")){
            e413.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(13,5).equals("")){
            e513.setBackground(Color.red);
        }
        /*NEW ROW*/
        if(!myPlane.returnEconomySeating(14,0).equals("")){
            e014.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(14,1).equals("")){
            e114.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(14,2).equals("")){
            e214.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(14,3).equals("")){
            e314.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(14,4).equals("")){
            e414.setBackground(Color.red);
        }
        if(!myPlane.returnEconomySeating(14,5).equals("")){
            e514.setBackground(Color.red);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JairlineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JairlineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JairlineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JairlineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    new JairlineGUI().setVisible(true);
                }
                catch(IOException e){
                    System.out.println("Didnt Work" + e);
                }
                catch(ClassNotFoundException r){
                    System.out.println("Didnt Work" + r);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookIt;
    private javax.swing.ButtonGroup btngropupClasses;
    private javax.swing.ButtonGroup btngroupSeatingPosition;
    private javax.swing.JButton e00;
    private javax.swing.JButton e01;
    private javax.swing.JButton e010;
    private javax.swing.JButton e011;
    private javax.swing.JButton e012;
    private javax.swing.JButton e013;
    private javax.swing.JButton e014;
    private javax.swing.JButton e02;
    private javax.swing.JButton e03;
    private javax.swing.JButton e04;
    private javax.swing.JButton e05;
    private javax.swing.JButton e06;
    private javax.swing.JButton e07;
    private javax.swing.JButton e08;
    private javax.swing.JButton e09;
    private javax.swing.JButton e10;
    private javax.swing.JButton e11;
    private javax.swing.JButton e110;
    private javax.swing.JButton e111;
    private javax.swing.JButton e112;
    private javax.swing.JButton e113;
    private javax.swing.JButton e114;
    private javax.swing.JButton e12;
    private javax.swing.JButton e13;
    private javax.swing.JButton e14;
    private javax.swing.JButton e15;
    private javax.swing.JButton e16;
    private javax.swing.JButton e17;
    private javax.swing.JButton e18;
    private javax.swing.JButton e19;
    private javax.swing.JButton e20;
    private javax.swing.JButton e21;
    private javax.swing.JButton e210;
    private javax.swing.JButton e211;
    private javax.swing.JButton e212;
    private javax.swing.JButton e213;
    private javax.swing.JButton e214;
    private javax.swing.JButton e22;
    private javax.swing.JButton e23;
    private javax.swing.JButton e24;
    private javax.swing.JButton e25;
    private javax.swing.JButton e26;
    private javax.swing.JButton e27;
    private javax.swing.JButton e28;
    private javax.swing.JButton e29;
    private javax.swing.JButton e30;
    private javax.swing.JButton e31;
    private javax.swing.JButton e310;
    private javax.swing.JButton e311;
    private javax.swing.JButton e312;
    private javax.swing.JButton e313;
    private javax.swing.JButton e314;
    private javax.swing.JButton e32;
    private javax.swing.JButton e33;
    private javax.swing.JButton e34;
    private javax.swing.JButton e35;
    private javax.swing.JButton e36;
    private javax.swing.JButton e37;
    private javax.swing.JButton e38;
    private javax.swing.JButton e39;
    private javax.swing.JButton e40;
    private javax.swing.JButton e41;
    private javax.swing.JButton e410;
    private javax.swing.JButton e411;
    private javax.swing.JButton e412;
    private javax.swing.JButton e413;
    private javax.swing.JButton e414;
    private javax.swing.JButton e42;
    private javax.swing.JButton e43;
    private javax.swing.JButton e44;
    private javax.swing.JButton e45;
    private javax.swing.JButton e46;
    private javax.swing.JButton e47;
    private javax.swing.JButton e48;
    private javax.swing.JButton e49;
    private javax.swing.JButton e50;
    private javax.swing.JButton e51;
    private javax.swing.JButton e510;
    private javax.swing.JButton e511;
    private javax.swing.JButton e512;
    private javax.swing.JButton e513;
    private javax.swing.JButton e514;
    private javax.swing.JButton e52;
    private javax.swing.JButton e53;
    private javax.swing.JButton e54;
    private javax.swing.JButton e55;
    private javax.swing.JButton e56;
    private javax.swing.JButton e57;
    private javax.swing.JButton e58;
    private javax.swing.JButton e59;
    private javax.swing.JButton f00;
    private javax.swing.JButton f01;
    private javax.swing.JButton f02;
    private javax.swing.JButton f03;
    private javax.swing.JButton f04;
    private javax.swing.JButton f10;
    private javax.swing.JButton f11;
    private javax.swing.JButton f12;
    private javax.swing.JButton f13;
    private javax.swing.JButton f14;
    private javax.swing.JButton f20;
    private javax.swing.JButton f21;
    private javax.swing.JButton f22;
    private javax.swing.JButton f23;
    private javax.swing.JButton f24;
    private javax.swing.JButton f30;
    private javax.swing.JButton f31;
    private javax.swing.JButton f32;
    private javax.swing.JButton f33;
    private javax.swing.JButton f34;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblEconomySeating;
    private javax.swing.JLabel lblFirstClassSeating;
    private javax.swing.JLabel lblRow;
    private javax.swing.JLabel lblRow0;
    private javax.swing.JLabel lblRow1;
    private javax.swing.JLabel lblRow10;
    private javax.swing.JLabel lblRow11;
    private javax.swing.JLabel lblRow12;
    private javax.swing.JLabel lblRow13;
    private javax.swing.JLabel lblRow14;
    private javax.swing.JLabel lblRow2;
    private javax.swing.JLabel lblRow3;
    private javax.swing.JLabel lblRow4;
    private javax.swing.JLabel lblRow5;
    private javax.swing.JLabel lblRow6;
    private javax.swing.JLabel lblRow7;
    private javax.swing.JLabel lblRow8;
    private javax.swing.JLabel lblRow9;
    private javax.swing.JLabel lblSeatAvability;
    private javax.swing.JLabel lblSeatingPosition;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTravelers;
    private javax.swing.JRadioButton rbtnAsile;
    private javax.swing.JRadioButton rbtnEconomyClass;
    private javax.swing.JRadioButton rbtnFirstClass;
    private javax.swing.JRadioButton rbtnMiddle;
    private javax.swing.JRadioButton rbtnWindow;
    private javax.swing.JTextField txtFldAvailableSeats;
    private javax.swing.JFormattedTextField txtFldNumTraveling;
    // End of variables declaration//GEN-END:variables
    private String classChoice;
    private String position;
    Airplane myPlane;
}
